import { next } from "@vercel/edge";

// Lightweight access gate for the static docs export served by Vercel.
//
// Goal (per product): stop one-click public access — NOT deep security. A single
// shared access key unlocks the whole site; visitors without a key leave their
// email through a request form, which we review and reply to with a link.
//
// Everything lives in this one file on purpose: the docs are a *static* Mintlify
// export (`out/`, regenerated by `mintlify export`), so any gate page committed
// into `out/` would be wiped on the next rebuild. Edge Middleware sits in front
// of the static output and is untouched by the export, so the gate survives.
//
// Fail-open: if DOCS_ACCESS_KEY is unset the gate is inert (site stays open). A
// missing env var must never lock everyone — including us — out. The gate only
// activates once DOCS_ACCESS_KEY is set in the Vercel project.

export const config = {
  // Gate every document, RSC payload and data fetch; let pure static assets
  // (JS/CSS/fonts/images, Next chunks) through. Those are only ever requested
  // *after* a page renders, so an un-unlocked visitor never reaches them, and
  // skipping them keeps edge invocations low. Page HTML (no extension) and RSC
  // (.txt/.json) are NOT excluded, so content stays behind the gate.
  matcher: [
    "/((?!_next/static|_next/image|_vercel|favicon|.*\\.(?:png|jpe?g|gif|svg|webp|avif|ico|css|js|map|woff2?|ttf|eot)$).*)",
  ],
};

const COOKIE = "deha_docs_access";
const COOKIE_MAX_AGE = 60 * 60 * 24 * 30; // 30 days
const REQUEST_PATH = "/__access/request";

const DEFAULT_LOG_URL = "https://deha.one/api/docs-access";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function readCookie(req: Request, name: string): string | null {
  const header = req.headers.get("cookie");
  if (!header) return null;
  for (const part of header.split(";")) {
    const idx = part.indexOf("=");
    if (idx === -1) continue;
    if (part.slice(0, idx).trim() === name) {
      return decodeURIComponent(part.slice(idx + 1).trim());
    }
  }
  return null;
}

function htmlResponse(html: string, status: number): Response {
  return new Response(html, {
    status,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-robots-tag": "noindex",
    },
  });
}

type GateState = "ask" | "bad-key" | "sent";

function gatePage(state: GateState, actionPath: string): string {
  const action = escapeHtml(actionPath || "/");
  const keyError =
    state === "bad-key"
      ? `<p class="err">That access key is not valid. Please check it and try again.</p>`
      : "";

  const body =
    state === "sent"
      ? `
        <h1>Request received</h1>
        <p class="lead">Thanks — we've recorded your request. We'll review it and email you a link to the documentation shortly.</p>
        <a class="back" href="/">&larr; Back</a>
      `
      : `
        <h1>DEHA ONE Documentation</h1>
        <p class="lead">This documentation is private. Enter your access key to continue.</p>

        <form method="GET" action="${action}" class="card">
          ${keyError}
          <label for="key">Access key</label>
          <input id="key" name="key" type="password" autocomplete="off" autofocus placeholder="Enter your access key" required />
          <button type="submit">Unlock</button>
        </form>

        <div class="divider"><span>Don't have a key?</span></div>

        <form method="POST" action="${escapeHtml(REQUEST_PATH)}" class="card">
          <p class="muted">Leave your email and we'll review your request and send you a link to the documentation.</p>
          <label for="email">Email</label>
          <input id="email" name="email" type="email" autocomplete="email" placeholder="you@company.com" required />
          <button type="submit" class="secondary">Request access</button>
        </form>
      `;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex,nofollow" />
<title>DEHA ONE Documentation — Access</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; min-height: 100vh; display: grid; place-items: center;
    background: radial-gradient(1200px 600px at 50% -10%, #16233a 0%, #0a0f1a 55%, #070b13 100%);
    color: #e6edf6;
    font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Inter, Arial, sans-serif;
    padding: 32px;
  }
  .wrap { width: 100%; max-width: 420px; }
  .brand { display: flex; align-items: center; gap: 10px; margin-bottom: 28px; }
  .brand .dot { width: 12px; height: 12px; border-radius: 3px; background: linear-gradient(135deg, #5b8cff, #8a6bff); box-shadow: 0 0 18px rgba(124,140,255,.6); }
  .brand span { font-weight: 600; letter-spacing: .02em; color: #aebbd0; font-size: 14px; }
  h1 { font-size: 22px; margin: 0 0 8px; letter-spacing: -.01em; }
  .lead { margin: 0 0 22px; color: #9fb0c7; font-size: 14.5px; line-height: 1.55; }
  .card { background: rgba(255,255,255,.03); border: 1px solid rgba(255,255,255,.08); border-radius: 14px; padding: 18px; margin-bottom: 16px; }
  label { display: block; font-size: 12.5px; color: #9fb0c7; margin-bottom: 8px; }
  input {
    width: 100%; padding: 11px 13px; border-radius: 10px; border: 1px solid rgba(255,255,255,.12);
    background: rgba(8,12,20,.6); color: #e6edf6; font-size: 14.5px; outline: none; transition: border-color .15s, box-shadow .15s;
  }
  input:focus { border-color: #5b8cff; box-shadow: 0 0 0 3px rgba(91,140,255,.18); }
  button {
    margin-top: 14px; width: 100%; padding: 11px 14px; border: 0; border-radius: 10px; cursor: pointer;
    font-size: 14.5px; font-weight: 600; color: #fff; background: linear-gradient(135deg, #5b8cff, #7c6bff);
    transition: filter .15s, transform .05s;
  }
  button:hover { filter: brightness(1.06); }
  button:active { transform: translateY(1px); }
  button.secondary { background: rgba(255,255,255,.07); border: 1px solid rgba(255,255,255,.12); }
  .muted { margin: 0 0 14px; color: #8294ad; font-size: 13px; line-height: 1.5; }
  .err { margin: 0 0 14px; color: #ff9a9a; font-size: 13px; }
  .divider { display: flex; align-items: center; gap: 12px; color: #6b7d96; font-size: 12px; margin: 4px 0 16px; }
  .divider::before, .divider::after { content: ""; height: 1px; flex: 1; background: rgba(255,255,255,.08); }
  .back { color: #7fa0ff; text-decoration: none; font-size: 14px; }
  .back:hover { text-decoration: underline; }
</style>
</head>
<body>
  <div class="wrap">
    <div class="brand"><span class="dot"></span><span>DEHA ONE</span></div>
    ${body}
  </div>
</body>
</html>`;
}

async function logAccessRequest(req: Request, email: string): Promise<void> {
  const url = process.env.DOCS_ACCESS_LOG_URL?.trim() || DEFAULT_LOG_URL;
  const token = process.env.DOCS_ACCESS_LOG_TOKEN?.trim();

  const ip =
    req.headers.get("x-real-ip") ||
    (req.headers.get("x-vercel-forwarded-for") || req.headers.get("x-forwarded-for") || "")
      .split(",")[0]
      .trim() ||
    "";

  const payload = {
    email,
    ip,
    country: (req.headers.get("x-vercel-ip-country") || "").toUpperCase(),
    ua: (req.headers.get("user-agent") || "").slice(0, 300),
    referer: (req.headers.get("referer") || "").slice(0, 300),
  };

  const headers: Record<string, string> = { "content-type": "application/json" };
  if (token) headers["authorization"] = `Bearer ${token}`;

  // Best-effort: never block the visitor on the log sink. Short timeout so a slow
  // or unreachable ingress can't stall the thank-you response.
  await fetch(url, {
    method: "POST",
    headers,
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout(2500),
  });
}

export default async function middleware(req: Request): Promise<Response> {
  const key = process.env.DOCS_ACCESS_KEY?.trim();
  if (!key) return next(); // fail-open: gate inert until the key is configured

  const url = new URL(req.url);

  // 1) Email request form submission.
  if (req.method === "POST" && url.pathname === REQUEST_PATH) {
    let email = "";
    try {
      const form = await req.formData();
      email = String(form.get("email") || "").trim().slice(0, 200);
    } catch {
      // Malformed body — fall through; still show the thank-you so we never 500.
    }
    if (email) {
      try {
        await logAccessRequest(req, email);
      } catch {
        // Logging is best-effort; the visitor's request still "succeeds".
      }
    }
    return htmlResponse(gatePage("sent", "/"), 200);
  }

  // 2) Key submission via ?key=…  → set cookie + redirect to the clean URL.
  const provided = url.searchParams.get("key");
  if (provided !== null) {
    if (provided === key) {
      url.searchParams.delete("key");
      const clean = url.pathname + (url.searchParams.size ? `?${url.searchParams}` : "");
      return new Response(null, {
        status: 302,
        headers: {
          Location: clean || "/",
          "Set-Cookie": `${COOKIE}=${encodeURIComponent(key)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${COOKIE_MAX_AGE}`,
        },
      });
    }
    return htmlResponse(gatePage("bad-key", url.pathname), 401);
  }

  // 3) Already unlocked?
  if (readCookie(req, COOKIE) === key) return next();

  // 4) Otherwise show the gate.
  return htmlResponse(gatePage("ask", url.pathname), 401);
}
